export const ERROR_LOGIN = "ERROR_LOGIN";
export const UNEXPECTED_ERROR = "UNEXPECTED_ERROR";
export const ERROR_REGISTER = "ERROR_REGISTER";
export const POST_ADDED = "POST_ADDED";
export const POST_REMOVED = "POST_REMOVED";
export const COMMENT_ADDED = "COMMENT_ADDED";
export const COMMENT_REMOVED = "COMMENT_REMOVED";
export const LOG_OUT = "LOG_OUT";
